site_name: boiled-fish-docs
copyright: Copyright © 2025 boiled-fish

nav:
  - about: about.md
  - index: index.md
  - CS144学习笔记:
    - 笔记1: CS144学习笔记/笔记1.md
    - Lab: CS144学习笔记/Lab/check1.md
  - Git: Git/《Git版本控制管理》.md
  - VMWare配置: VMWare配置/VPN网络配置.md
  - 系统架构设计师备考:
    - 考试简介&备考建议: 系统架构设计师备考/考试简介&备考建议.md
    - 计算机系统基础: 系统架构设计师备考/计算机系统基础.md
    - images:
      - Pasted image 20260105132939: 系统架构设计师备考/images/Pasted image 20260105132939.png
      - Pasted image 20260105164939: 系统架构设计师备考/images/Pasted image 20260105164939.png
      - Pasted image 20260105165350: 系统架构设计师备考/images/Pasted image 20260105165350.png
      - Pasted image 20260105173248: 系统架构设计师备考/images/Pasted image 20260105173248.png
      - Pasted image 20260106094807: 系统架构设计师备考/images/Pasted image 20260106094807.png
      - Pasted image 20260106110234: 系统架构设计师备考/images/Pasted image 20260106110234.png
      - Pasted image 20260106111910: 系统架构设计师备考/images/Pasted image 20260106111910.png
      - Pasted image 20260106112121: 系统架构设计师备考/images/Pasted image 20260106112121.png
      - Pasted image 20260107091131: 系统架构设计师备考/images/Pasted image 20260107091131.png
      - Pasted image 20260107092736: 系统架构设计师备考/images/Pasted image 20260107092736.png
      - Pasted image 20260107095406: 系统架构设计师备考/images/Pasted image 20260107095406.png
      - Pasted image 20260107101257: 系统架构设计师备考/images/Pasted image 20260107101257.png
      - Pasted image 20260107102537: 系统架构设计师备考/images/Pasted image 20260107102537.png
      - Pasted image 20260108145056: 系统架构设计师备考/images/Pasted image 20260108145056.png
theme: readthedocs

markdown_extensions:
  - admonition  # 提示块
  - footnotes  # 脚注
  - meta  # 定义元数据，通过文章上下文控制，如disqus
  - pymdownx.caret  # 下划线上标
  - pymdownx.tilde  # 删除线下标
  - pymdownx.critic  # 增加删除修改高亮注释，可修饰行内或段落
  - pymdownx.details  # 提示块可折叠
  - pymdownx.inlinehilite  # 行内代码高亮
  - pymdownx.mark  # 文本高亮
  - pymdownx.smartsymbols  # 符号转换
  - pymdownx.superfences  # 代码嵌套在列表里
  - codehilite:    # 代码高亮，显示行号
      guess_lang: false
      linenums: true
  - toc:  # 锚点
      permalink: true
#  - pymdownx.arithmatex  # 数学公式
  - pymdownx.betterem:  # 对加粗和斜体更好的检测
      smart_enable: all
#  - pymdownx.emoji:  # 表情
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
#  - pymdownx.magiclink  # 自动识别超链接
  - pymdownx.tasklist:  # 复选框checklist
      custom_checkbox: true